language: ruby
rvm:
- ruby-head
deploy:
  provider: heroku
  app: gentle-escarpment-31458
  api_key:
    secure: sPT0UAZIPxdpT97Paq3nRmPsEOSN1crFXMZ9keUvJSjX/XnWEri3cXF98MsaiUDwSatKXq/S5b88zv5lDBVktR5lp19ldP5U8+S5Iy1tCyqRi36K/czaIQJNMGm8Y0B4mOREY3JxKH9Ieg1VAK7Wktul/AeGbdxVBmtIE9toQDF4Ri26zXV+m2WuTYqq6M0sbauxZHECSTFsRIAI4aCiFg5Rp9r54SRXrJw+hrFgd1TbROFsuouqow33CnCaRH9sHapkg9SIqxmc/MZr9vlta19rVrd1Z7CP0AD6tMVWKQMsA9cBVL//YefmHueGljs9nuJLkRxPZmfUCu0VUpZhKekJvHvo08uFRnAhoV+/8OwYmUdqYBcaR25i+X8iR8Fz3qtEbTeUQc4WdOYa4c9uQ14wJR1hBH1ucRVSk8qE7cLIygJX7ZltfwhrLMV/Qnv6Se4CejoVLJUr4pHraSaoKkgtF90Hx1XgNOiFWBlhSjMtveH+Dmh5hzQo3T9gc200oesh7SbTrOQ9y6U6ScKbK2nTnOTs0CTUhK32sgIMCzU2StKjnUZepDMS+QVw65Gb88lekdH/Msql9QhA4TPc8d2Gaew/IUjXBTeEWJH1sUyhp2L3zpJpxoWreWhF7eDivovnkfHwYgHzBHehdX/FItoZN5yAZnFLjCwkdDeZw4Y=
